Added functionality to export JVM information
padaiyal/jVaidhiyar pull request #7
Opened 2021-02-08 22:34 UTC by the-c0d3br34k3r

## Description
Closes #4.
All JVM related information provided by JVMUtility can
now be exported to a JSON file.

## Author's Checklist
- [ ] **These changes don't break existing dependants.** If they do, and you suggest to proceed, 
please explain why.

## Reviewer's Checklist
- [ ] **All classes have documentation comments.**
- [ ] **All methods have documentation comments.**
- [ ] **No parameters are hardcoded.** Should be loaded as properties instead. If there needs to be hardcoded properties, explain why.
- [ ] **All information to be logged/displayed to the user are internationalized.** If not, explain why. 
- [ ] **README.md has been updated if needed.**
- [ ] **pom.xml version is set to the latest date** If not, explain why.

## Assignee's Checklist
- [ ] **All GitHub action checks have passed.**
- [ ] **All reviewers have approved.**
- [ ] **Relevant documentation has been updated if needed.**
- [ ] **pom.xml version is set to the latest date** If not, explain why.

2021-02-08 23:39 UTC, silvs110 requested changes

2021-02-08 23:39 UTC, silvs110 commented on src/main/java/org/padaiyal/utilities/vaidhiyar/JvmUtility.java
> +      throw new IllegalArgumentException("destinationDirectory path has to exist.");
Internationalize exception message

2021-02-08 23:39 UTC, silvs110 commented on src/main/java/org/padaiyal/utilities/vaidhiyar/JvmUtility.java
> +      throw new IllegalArgumentException("destinationDirectory path has to be a directory.");
Internationalize exception message

2021-02-09 19:13 UTC, the-c0d3br34k3r commented on src/main/java/org/padaiyal/utilities/vaidhiyar/JvmUtility.java
> +      throw new IllegalArgumentException("destinationDirectory path has to exist.");
Done.

2021-02-09 19:13 UTC, the-c0d3br34k3r commented on src/main/java/org/padaiyal/utilities/vaidhiyar/JvmUtility.java
> +      throw new IllegalArgumentException("destinationDirectory path has to be a directory.");
Done.

2021-02-09 23:44 UTC, silvs110 requested changes

2021-02-09 23:44 UTC, silvs110 commented on src/main/java/org/padaiyal/utilities/vaidhiyar/JvmUtility.java
> +   * @param destinationDirectory  Directory in which to create the JSOn file.
replace 'JSOn' -> 'JSON'

2021-02-10 00:32 UTC, the-c0d3br34k3r commented on src/main/java/org/padaiyal/utilities/vaidhiyar/JvmUtility.java
> +   * @param destinationDirectory  Directory in which to create the JSOn file.
Done.

2021-02-10 00:36 UTC, silvs110 approved these changes

2021-02-10 00:37 UTC, merged