Updated README.md
padaiyal/jVaidhiyar pull request #8
Opened 2021-02-09 23:30 UTC by the-c0d3br34k3r

## Description
Closes #1.

## Author's Checklist
- [ ] **These changes don't break existing dependants.** If they do, and you suggest to proceed, 
please explain why.

## Reviewer's Checklist
- [ ] **All classes have documentation comments.**
- [ ] **All methods have documentation comments.**
- [ ] **No parameters are hardcoded.** Should be loaded as properties instead. If there needs to be hardcoded properties, explain why.
- [ ] **All information to be logged/displayed to the user are internationalized.** If not, explain why. 
- [ ] **README.md has been updated if needed.**
- [ ] **pom.xml version is set to the latest date** If not, explain why.

## Assignee's Checklist
- [ ] **All GitHub action checks have passed.**
- [ ] **All reviewers have approved.**
- [ ] **Relevant documentation has been updated if needed.**
- [ ] **pom.xml version is set to the latest date** If not, explain why.

2021-02-09 23:52 UTC, silvs110 requested changes

2021-02-09 23:52 UTC, silvs110 commented on README.md
> +For more such examples, checkout [JvmUtilityTest](https://github.com/padaiyal/jCommandLine/tree/main/src/test/java/org/padaiyal/utilities/vaidhiyar/JvmUtilityTest.java)
```suggestion
For more such examples, checkout [JvmUtilityTest](https://github.com/padaiyal/jVaidhiyar/tree/main/src/test/java/org/padaiyal/utilities/vaidhiyar/JvmUtilityTest.java)
```

2021-02-09 23:52 UTC, silvs110 commented on README.md
Missing description

2021-02-10 00:29 UTC, the-c0d3br34k3r commented on README.md
Done.

2021-02-10 00:30 UTC, the-c0d3br34k3r commented on README.md
> +For more such examples, checkout [JvmUtilityTest](https://github.com/padaiyal/jCommandLine/tree/main/src/test/java/org/padaiyal/utilities/vaidhiyar/JvmUtilityTest.java)
Done.

2021-02-10 01:01 UTC, silvs110 approved these changes

2021-02-10 01:03 UTC, merged